### ISSUE TITLE
是否可以在win10 上运行吗

### ISSUE THREAD

**Issue by zhou431496** [BillyXYB/TransEditor#2]
请问大佬，该程序可以在win10上运行嘛

**Comment by BillyXYB** [comment]
We tested our program on Linux-based machines. But if the dependencies support win10 and the environment is successfully configured, one should be able to run the code.

**Comment by zhou431496** [comment]
我们无法在oneDriver上下载预训练模型，可否提供谷歌云盘的链接。我们感激不尽
