### ISSUE TITLE
pSp model_paths ?

### ISSUE THREAD

**Issue by Johnren1111** [BillyXYB/TransEditor#7]
I cannot find the model called model_ir_se50.pth ! Can you send me the url? thanks

**Comment by yinyueqin** [comment]
Hi, you can find in [pixel2style2pixel](https://github.com/eladrich/pixel2style2pixel), or download from [google drive](https://drive.google.com/file/d/1KW7bjndL3QG3sxBbZxreGHigcCCpsDgn/view).

**Comment by Johnren1111** [comment]
Thanks！



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 10, 2022 11:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BillyXYB/TransEditor] pSp model_paths ? (Issue #7)




 
Hi, you can find in pixel2style2pixel, or download from google drive.
