### ISSUE TITLE
celebahq-classifiers

### ISSUE THREAD

**Issue by Johnren1111** [BillyXYB/TransEditor#8]
I can not download them! please provide me new url! thanks!

**Comment by yinyueqin** [comment]
Hi, you can download [here.](http://latent-composition.csail.mit.edu/other_projects/gan_ensembling/zips/pretrained_classifiers.zip)

**Comment by Johnren1111** [comment]
thanks！



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 12, 2022 17:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BillyXYB/TransEditor] celebahq-classifiers (Issue #8)




 
Hi, you can download here.

**Comment by GreenLimeSia** [comment]
The url seem to be broken, could you kindly release it in your spare time? @yinyueqin
